
CREATE TABLE JOB_TABLE
(
  JOB_NAME   TEXT  NOT NULL,
  SEQ_ID_JOB FLOAT NOT NULL,
  PRIMARY KEY (SEQ_ID_JOB)
);

CREATE TABLE MEMBER_TABLE
(
  MEMBER_NAME   TEXT  NOT NULL,
  SEQ_ID_MEMBER FLOAT NOT NULL,
  SEQ_ID_JOB    FLOAT NOT NULL,
  PRIMARY KEY (SEQ_ID_MEMBER)
);
--
--ALTER TABLE MEMBER_TABLE
--  ADD CONSTRAINT FK_JOB_TABLE_TO_MEMBER_TABLE
--    FOREIGN KEY (SEQ_ID_JOB)
--    REFERENCES JOB_TABLE (SEQ_ID_JOB);
